@startuml
class Symptom {
  string identifier
  CodeableConcept symptomCode
  Patient affectedPatient
  CareTeamMember recorder
  Annotation 0..* symptomDescription
  CodeableConcept 0..1 clinicalCourse
  CodeableConcept 0..1 trend
}
Symptom *-- "0..*" KeyFeatures
class KeyFeatures {
  BodyStructure 0..* location
}
KeyFeatures *-- "0..1" Quality
class Quality {
  code scaleCode
  CodeableConceptOrString value
}
KeyFeatures *-- "0..1" Severity
class Severity {
  code scaleCode
  CodeableConceptOrString value
}
KeyFeatures *-- "0..*" FunctionalImpact
class FunctionalImpact {
  Annotation 0..1 note
  CodeableConcept 0..1 affectiveGrade
  code scaleCode
  CodeableConceptOrString value
}
KeyFeatures *-- "0..*" SurroundingEvents
class SurroundingEvents {
  CodeableConcept 0..* otherEvents
}
SurroundingEvents *-- "0..*" Triggers
class Triggers {
  CodeableConcept triggerCode
  CodeableConceptOrString value
  Annotation 0..1 note
}
SurroundingEvents *-- "0..*" ExacerbatingFactors
class ExacerbatingFactors {
  CodeableReference 0..* factor
  Medication 0..* relatedMedication
  Annotation 0..1 note
}
SurroundingEvents *-- "0..*" AlleviatingFactors
class AlleviatingFactors {
  CodeableReference 0..* factor
  Medication 0..* relatedMedication
  Annotation 0..1 note
}

Symptom *-- "0..1" Timing
class Timing {
  CodeableConcept 0..1 speed
  dateTimeOrPeriod 0..1 onset
  Annotation 0..1 note
  CodableConceptOrDuration 0..1 duration
  Quantity 0..1 frequency
  CodeableConcept 0..1 timePattern
}

Symptom *-- Metadata
class Metadata {
dateTime documentationDate
dateTime issued
}

@enduml
