@startuml
class Symptom {
  string identifier
  CodeableConcept symptomCode
  boolean presentFlag
  Patient affectedPatient
  CareTeamMember reporter
  Annotation 0..* symptomDescription
  CodeableConcept 0..* location
  CodeableConcept 0..1 clinicalCourse
  CodeableConcept 0..1 trend
  Condition 0..* associatedConditions
}
Symptom *-- "0..*" Symptom : associatedSymptoms
Symptom *-- "0..*" KeyFeatures
class KeyFeatures {
  CodeableConceptOrRatio 0..1 frequency
}
KeyFeatures *-- "0..1" Quality
class Quality {
  Annotation 0..1 note
  code 0..1 scaleCode
  CodeableConcept value
}
KeyFeatures *-- "0..1" Severity
class Severity {
  Annotation 0..1 note
  code 0..1 scaleCode
  CodeableConcept value
}
KeyFeatures *-- "0..1" Impact
class Impact {
  Annotation 0..1 note
  code 0..1 scaleCode
  CodeableConcept value
}
KeyFeatures *-- "0..1" SurroundingEvents
class SurroundingEvents {
  CodeableConcept 0..* otherEvents
}
SurroundingEvents *-- "0..*" TriggersOrExacerbatingFactors
class TriggersOrExacerbatingFactors {
  CodeableConcept factor
  Medication 0..* relatedMedication
  Annotation 0..1 note
}
SurroundingEvents *-- "0..*" AlleviatingFactors
class AlleviatingFactors {
  CodeableConcept factor
  Medication 0..* relatedMedication
  Annotation 0..1 note
}

Symptom *-- "0..1" Timing
class Timing {
  CodeableConcept 0..1 speed
  dateTimeOrPeriod 0..1 onset
  Annotation 0..1 note
  Duration 0..1 duration
}

Symptom *-- Metadata
class Metadata {
dateTime documentationDate
dateTime issued
}

@enduml
