@startuml
class Symptom {
  string identifier
  code symptomCode
  boolean presentFlag
  Patient affectedPatient
  PatientOrRelatedPerson reporter
  Annotation 0..* symptomDescription
  code 0..1 clinicalCourse
  code 0..1 trend
  Condition 0..* associatedConditions
}
Symptom *-- "0..*" Symptom : associatedSymptoms
Symptom *-- "0..*" KeyFeatures
class KeyFeatures {
}
KeyFeatures *-- "0..*" Location
class Location {
  code 1..1 code
  string 0..* qualifier
}
KeyFeatures *-- "0..1" Frequency
class Frequency {
  string 0..1 quality
  Quantity 0..1 quantity
}
KeyFeatures *-- "0..*" Quality
class Quality {
  Annotation 0..1 note
  code 0..1 scaleCode
  code value
}
KeyFeatures *-- "0..1" Severity
class Severity {
  Annotation 0..1 note
  code 0..1 scaleCode
  code value
}
KeyFeatures *-- "0..1" Impact
class Impact {
  Annotation 0..1 note
  code 0..1 scaleCode
  code value
}
KeyFeatures *-- "0..1" SurroundingEvents
class SurroundingEvents {
  code 0..* otherEvents
}
SurroundingEvents *-- "0..*" TriggersOrExacerbatingFactors
class TriggersOrExacerbatingFactors {
  code factor
  Medication 0..* relatedMedication
  Annotation 0..1 note
}
SurroundingEvents *-- "0..*" AlleviatingFactors
class AlleviatingFactors {
  code factor
  Medication 0..* relatedMedication
  Annotation 0..1 note
}

Symptom *-- "0..1" Timing
class Timing {
  code 0..1 speed
  dateTimeOrPeriod 0..1 onset
  Annotation 0..1 note
  Duration 0..1 duration
}

Symptom *-- Metadata
class Metadata {
dateTime documentationDate
dateTime issued
}

@enduml
